/**
 * This package contains the code generated by the Protocol-Buffer tool.
 * <p>
 * For most use-cases it is not necessary to use code from this package when using the library.
 * Only for some custom {@link eu.antidotedb.client.transformer.Transformer} implementations it might be necessary to use this package.
 */
package eu.antidotedb.antidotepb;